/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fact.h"

int *
fact_1_svc(number *argp, struct svc_req *rqstp)
{
	static int  result,n,num;
	int i;
	n=argp->a;
	num=1;
	printf("Received no is:- %d",n);
    for(i=n;i>0;i--)
    {
    num=num*i;
    }
	result=num;

	return &result;
}
